name: Generar-WAR-Auto
on:
    # Se activa al terminar el flujo de tests
  workflow_run:
    workflows: ["Test-SO-Manual"] 
    types:
      - completed

jobs:
  build-job:
    # Solo se ejecuta si los tests de la ejecucion previa fueron exitosos
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      # Generamos el WAR. ademas nos saltsamos los tests porque ya los hemos comprobado
      - name: Build WAR
        run: mvn package -DskipTests
        
        # Almacenamos el archivo para que sea descargable
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: proyecto-war
          path: target/*.war