name: Generar-WAR-Auto

on:
  workflow_run:
    workflows: ["Test-SO-Manual"] # Debe coincidir con el 'name' del anterior
    types:
      - completed

jobs:
  build-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build WAR
        run: mvn package -DskipTests
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: proyecto-war
          path: target/*.war