
name: Sistemas operativos test

# workflow_dispatch permite lanzar la ejecucion manualmente desde github
on:
  workflow_dispatch:

jobs:
  test:
    # ejecutar en dos sistemas operativos simultaneamente
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    # sistema operativo de la matriz se ejecuta esta instancia
    runs-on: ${{ matrix.os }}

    steps:
      # Descargar el codigo fuente del repositorio
      - name: Checkout del codigo
        uses: actions/checkout@v4

      # Configurar el entorno de Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Ejecutar los tests de Spring Boot
      - name: Ejecutar Tests con Maven
        run: mvn test